export const frasesEspera = [
    "Mientras esperas los resultados, tal vez deberías considerar una carrera en la adivinación.",
    "Mientras aguardas los resultados, recuerda que la paciencia es una virtud que los perdedores practican mucho.",
    "Esperar los resultados es como esperar a que un unicornio te traiga la buena suerte, muy poco probable.",
    "La ansiedad por los resultados es directamente proporcional a tu falta de confianza en tus decisiones.",
    "No te preocupes por los resultados, al fin y al cabo, la vida es solo un juego en el que siempre pierdes.",
    "Mientras esperas los resultados, recuerda que la esperanza es solo una ilusión generada por tu falta de información.",
    "Es muy probable que no sirvas para las apuestas, pero al menos eres bueno esperando malas noticias.",
    "Mientras esperas los resultados, recuerda que el destino siempre guarda una buena dosis de decepción para ti.",
    "Esperar los resultados es como esperar que un elefante equilibre una pelota de playa en su nariz, una verdadera fantasía.",
    "No te preocupes por los resultados, al final del día, el universo siempre encuentra la manera de burlarse de tus expectativas.",
    "Mientras esperas los resultados, recuerda que la vida es como una apuesta, siempre pierdes, solo cambian las reglas del juego.",
    "Esperar los resultados es como esperar que un pez vuele con alas, definitivamente no es algo que debas apostar.",
    "No te preocupes por los resultados, recuerda que la felicidad no está en ganar, sino en reírte de tus propias derrotas.",
    "Mientras esperas los resultados, considera la posibilidad de que tu suerte esté tomando unas largas vacaciones en las Bahamas.",
    "Es muy probable que los resultados te decepcionen, pero recuerda que el verdadero fracaso está en no intentarlo en absoluto.",
    "Esperar los resultados es como esperar que una pizza te hable y te diga que vas a ganar, simplemente no va a suceder.",
    "No te preocupes por los resultados, recuerda que la vida es solo una serie de apuestas en las que siempre pierdes.",
    "Mientras esperas los resultados, tal vez deberías considerar un cambio de carrera y convertirte en un juez de competiciones de babosas.",
    "Es muy probable que los resultados te hagan darte cuenta de que apostar no es lo tuyo, pero al menos tendrás una historia graciosa que contar.",
    "Esperar los resultados es como esperar que un gato te diga tu futuro, simplemente no es algo en lo que debas confiar.",
    "No te preocupes por los resultados, al final todo se reduce a una cuestión de azar, y tú pareces ser el rey de las malas cartas.",
    "Mientras esperas los resultados, recuerda que la vida es una montaña rusa y, en este momento, estás en la parte más aburrida.",
    "Es muy probable que los resultados te dejen con una sensación de vacío, pero recuerda que siempre puedes llenarlo con comida chatarra y risas.",
    "Esperar los resultados es como esperar que una planta de tomate crezca billetes de lotería, no es algo realista.",
    "No te preocupes por los resultados, al fin y al cabo, el éxito y el fracaso son solo conceptos inventados para hacernos sentir mejor o peor.",
    "Mientras esperas los resultados, recuerda que en el gran juego de la vida, siempre ganas algo, incluso si es solo experiencia para futuros fracasos.",
];
const frasesEspera = [
    "Mientras esperas los resultados, los astros se ríen de tus decisiones.",
    "Esperar los resultados es como ver un partido de fútbol donde todos los jugadores son ciegos.",
    "No te preocupes por los resultados, tus apuestas son el mejor chiste que has contado.",
    "Mientras aguardas los resultados, la suerte está en el mismo lugar donde dejaste tus habilidades para apostar: en el olvido.",
    "Mientras aguardas los resultados, recuerda que la paciencia es una virtud que los perdedores practican mucho.",
    "No te preocupes por los resultados, al fin y al cabo, la vida es solo un juego en el que siempre pierdes.",
    "No te preocupes por los resultados, al menos eres bueno en algo: en ser un maestro del fracaso.",
    "Mientras esperas los resultados, recuerda que el destino tiene un sentido del humor muy peculiar, y tú eres la broma principal.",
    "Es muy probable que los resultados te hagan preguntarte si el universo está conspirando en tu contra o simplemente tienes muy mala suerte.",
    "Mientras esperas los resultados, recuerda que la esperanza es solo una ilusión generada por tu falta de información.",
    "No te preocupes por los resultados, siempre puedes culpar a la mala suerte, aunque en realidad tu habilidad para perder es impresionante.",
    "Mientras esperas los resultados, considera la posibilidad de escribir un libro titulado 'Cómo perder dinero en 5 sencillos pasos'.",
    "Es muy probable que los resultados te hagan cuestionar tus habilidades para tomar decisiones, pero al menos tienes una buena historia de terror para contar.",
    "No te preocupes por los resultados, al final del día, el universo siempre encuentra la manera de burlarse de tus expectativas.",
    "No te preocupes por los resultados, recuerda que siempre puedes decir que estás practicando para ser el mejor perdedor del mundo.",
    "Mientras esperas los resultados, recuerda que la vida es como una apuesta, siempre pierdes, solo cambian las formas de hacerlo.",
    "Es muy probable que los resultados te hagan sentir como el protagonista de una película de comedia sin gracia, siempre esperando el golpe final.",
    "No te preocupes por los resultados, al final todo se reduce a una cuestión de azar, y tú pareces ser el rey de las malas cartas.",
    "Mientras esperas los resultados, recuerda que en el gran juego de la vida, siempre ganas algo, incluso si es solo experiencia para futuros fracasos.",
    "Mientras esperas los resultados, considera la posibilidad de ofrecer tus servicios como ejemplo viviente de cómo no apostar.",
    "Es muy probable que los resultados te hagan pensar en cambiar tu nombre a 'Mr. Desastre' o 'Mr Fracaso' como una marca personal.",
    "GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "No te preocupes por los resultados, recuerda que siempre puedes presumir de ser un experto en tomar las peores decisiones posibles.",
    "Mientras esperas los resultados, ten en cuenta que el karma parece estar disfrutando mucho de tus apuestas.",
    "Es muy probable que los resultados te hagan sentir como el bufón de las apuestas, siempre haciendo reír a los demás con tus derrotas.",
    "Vas a caer chupetin trujillo, Yo la realeza MAKANAKI, LA PUTA FAMAAAAA, GAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
];

export const frasesAcertadas = [
    "Suerte de principiante, algo es algo.",
    "Vas acertando algunas, aunque no todas.",
    "No te emociones, aún falta ver el resultado de las otras apuestas.",
    "Parece que has tenido un poco de suerte, por ahora.",
    "No te confíes, esto puede cambiar en cualquier momento.",
    "No te ilusiones demasiado, esto es solo el principio.",
    "No te sientas tan orgulloso, todavía hay margen de error.",
    "No te creas tan bueno, aún falta mucho por demostrar.",
    "No te apresures a celebrar, la suerte puede cambiar en cualquier instante.",
    "No te emociones demasiado, la fortuna puede ser efímera.",
    "No te adelantes, las apuestas aún no están cerradas.",
    "No te hagas ilusiones, todavía hay mucho en juego.",
    "No te confíes en exceso, esto puede ser solo un golpe de suerte.",
    "No te emociones tanto, aún falta ver cómo terminan las otras apuestas.",
    "No te creas el mejor, todavía tienes mucho por aprender.",
    "No te jactes demasiado, esto puede ser solo una casualidad.",
    "No te sientas tan triunfante, las cosas pueden cambiar en un instante.",
    "No te engañes, esto puede ser solo un espejismo de éxito.",
    "No te deslumbres tanto, la suerte puede ser caprichosa.",
    "No te ilusiones demasiado, las apuestas pueden ser traicioneras.",
    "No te vuelvas loco, esto es solo un pequeño avance.",
    "No te creas el mejor apostador, todavía estás en la etapa inicial.",
    "No te hagas muchas expectativas, esto puede ser solo una excepción.",
    "No te confíes tanto, esto podría ser solo una casualidad momentánea.",
    "No te creas invencible, las apuestas siempre tienen su riesgo.",
];
export const frasesNoAcertadas = [
    "¡No sirves para esto! ¿Ya quedaste en la ruina?",
    "Ni una sola apuesta acertada, parece que deberías buscar otro pasatiempo.",
    "Cero aciertos, estás dejando un legado de fracasos.",
    "Todas fallidas, ¿alguna vez consideraste la posibilidad de retirarte?",
    "Ningún acierto, parece que tu suerte se fue de vacaciones.",
    "¿Apostar? No es lo tuyo, mejor dedícate a otra cosa.",
    "Cada apuesta equivocada te acerca más a la bancarrota.",
    "Ninguna ganancia, ¿cuánto tiempo más piensas desperdiciar en esto?",
    "Ni siquiera un acierto por casualidad, tu racha de fracasos es impresionante.",
    "¿No has pensado en donar tu dinero a una causa más noble?",
    "Cero éxitos, ¿ya consideraste dejar de intentarlo?",
    "Tus apuestas son una broma, pero nadie está riendo contigo.",
    "No acertaste ninguna, pareciera que estás siguiendo un manual de errores.",
    "¿Estás seguro de que sabes cómo funciona esto? Porque los resultados dicen lo contrario.",
    "Ningún acierto, tu destreza para perder dinero es impresionante.",
    "Ni una sola apuesta ganadora, pareciera que el universo conspira en tu contra.",
    "Cero aciertos, tu habilidad para fallar es digna de admiración.",
    "¿Quieres un consejo? Deja de apostar, no tienes futuro en esto.",
    "Ningún triunfo a la vista, parece que tienes un imán para las derrotas.",
    "No acertaste ninguna, pero al menos eres constante en tu fracaso.",
    "¿Ya te quedaste sin dinero? Tal vez deberías aprender a administrarlo mejor.",
    "Cada apuesta fallida es un recordatorio de tu falta de talento en esto.",
    "Ni una sola victoria, ¿alguna vez consideraste cambiar de estrategia?",
    "Ningún acierto, ¿alguna vez te has preguntado si simplemente no eres bueno en esto?",
    "Cero aciertos, parece que tienes una habilidad especial para perder en todo.",
    "¿Quedaste en bancarrota? No te preocupes, al menos eres constante en tu fracaso.",
];
export const frases50 = [
    "¡Felicitaciones! Lograste acertar la mitad, pero aún falta mucho para ser decente en esto.",
    "Has acertado la mitad, pero tampoco te emociones demasiado, todavía tienes mucho por mejorar.",
    "Un 50% de aciertos, supongo que es mejor que nada, aunque sigue siendo bastante mediocre.",
    "Lograste acertar la mitad de las apuestas, así que técnicamente puedes llamarte 'medianamente competente'.",
    "La suerte estuvo de tu lado en la mitad de las apuestas, pero no te hagas ilusiones, eso no te convierte en un experto.",
    "50% de aciertos, eres como un reloj roto que da la hora correcta dos veces al día.",
    "Mitad de tus apuestas fueron correctas, pero eso no es motivo para celebrar, es más bien motivo para preocuparse.",
    "Lograste acertar la mitad, lo cual demuestra que tienes una habilidad impresionante para equivocarte también en la mitad.",
    "Un 50% de aciertos, eso significa que estás a la par con un mono lanzando dardos al azar.",
    "Felicidades, tienes una habilidad sobresaliente para estar equivocado la mitad del tiempo.",
    "Has logrado acertar la mitad, lo cual prueba que tienes el potencial de ser igual de malo o igual de bueno la próxima vez.",
    "50% de aciertos, es como si tus decisiones fueran determinadas por un gato jugando con una bola de cristal.",
    "La mitad de tus apuestas fueron correctas, pero aún estás lejos de ser considerado una persona decente en esto.",
    "Lograste acertar la mitad, parece que tienes una habilidad especial para estar en el punto medio del fracaso.",
    "Un 50% de aciertos, eso es suficiente para demostrar que tu suerte fluctúa entre mediocre y terrible.",
    "Felicidades, has alcanzado la excelencia de estar en el promedio de los perdedores.",
    "Has logrado acertar la mitad de las apuestas, pero recuerda que en este mundo ser mediocre no te llevará muy lejos.",
    "50% de aciertos, lo cual demuestra que eres igual de malo que alguien que simplemente elige al azar.",
    "Lograste acertar la mitad, aunque eso no dice mucho considerando que las probabilidades estaban a tu favor.",
    "Un 50% de aciertos, justo en el punto medio entre el éxito y el fracaso absoluto.",
    "Felicidades, tu habilidad para acertar la mitad de las apuestas es comparable a la de una moneda lanzada al aire.",
    "Has logrado acertar la mitad, aunque eso no es nada para presumir considerando que solo tienes dos opciones.",
    "50% de aciertos, al menos puedes decir que eres constante en tu mediocridad.",
    "Lograste acertar la mitad de las apuestas, lo cual significa que tienes un talento especial para estar justo en el medio de la mediocridad.",
    "Un 50% de aciertos, sigue así y tal vez algún día llegarás a ser decente en esto.",
    "Felicidades por tu 50% de aciertos, ahora puedes ir a festejar al club de los perdedores moderadamente exitosos.",
];
